### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wenwenwen888** [zhukunpenglinyutong/electron-tiny-img#1]
压缩完之后还是不要覆盖原图好，毕竟谁也不知道压缩出来的效果满不满意。或者做个选择，让用户选择是否覆盖

**Comment by zhukunpenglinyutong** [comment]
> 压缩完之后还是不要覆盖原图好，毕竟谁也不知道压缩出来的效果满不满意。

是的，我会在下个版本增加 这个选项，多谢
