### ISSUE TITLE
疑惑，为何图片需要上传到服务器

### ISSUE THREAD

**Issue by chenfanfang** [zhukunpenglinyutong/electron-tiny-img#2]
疑惑，为何图片需要上传到服务器，不清楚是技术上的问题还是刻意收集图片资源

**Comment by zhukunpenglinyutong** [comment]
因为底层调用的是 tinypng Api，和使用 tinypng 网址一样，都需要上传图片，然后 tinypng 服务器返回 压缩后的图片内容

使用本工具的好处是，破解了 tinypng Api，可以绕过 tinypng 收费，也支持更大（10MB）的压缩尺寸，和更便捷的交互方法

备注：tinypng网址：https://tinypng.com/
